plugins {
    id 'com.android.application'
    id 'com.google.gms.google-services'
}

android {
    namespace 'com.sawarisetu.app'
    compileSdk 35

    defaultConfig {
        applicationId 'com.sawarisetu.app'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '1.0'
    }
}
